name: Github Action Test

on:   
   pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      name: Checkout repo
      
    - name: Run App size diff
      uses: ./
      with:
        baseAppPath: test/assets/test.apk
        baseAppLabel: Base app
        targetAppPath: test/assets/test.apk
        targetAppLabel: Target app
        summaryOutputPath: summary.md
        metrics: apkSize, installSize, arscFile, nativeLibs, dexFiles
        thresholds: 10, 10, 10, 10, 10

    - name: Print summary
      run: cat summary.md
