# This is a basic workflow to help you get started with Actions

name: App Size Check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    
      # Runs a single command using the runners shell
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Apk size Difference
        uses: ./
        with:
          baseAppPath: test/assets/test.apk
          baseAppLabel: Base app
          targetAppPath: test/assets/test.apk
          targetAppLabel: Target app
          summaryOutputPath: summary.md
          metrics: apkSize, installSize, arscFile, nativeLibs, dexFiles
          thresholds: 10, 10, 10, 10, 10
          
      - name: Print
        run: cat summary.md

 
