name: Android Feature Branch CI

on:
  pull_request:
    branches: [master]
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit Test
        run: ./gradlew testDebugUnitTest
        continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step
     
      - name: Code Coverage   
        uses: ziishaned/jest-reporter-action@v0.0.1
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         test-command: "yarn jest --coverage"  
         
 

